# Use Node.js image as base
FROM node:16

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY frontend/package*.json ./

# Install frontend dependencies
RUN npm install

# Copy the rest of the frontend files
COPY ./frontend .

# Expose the port used by the React development server
EXPOSE 3000

# Start the React development server
CMD ["npm", "start"]