version: '3.8'

services:
  frontend:
    image: clintbeastwood/appify-frontend:latest # Pull the frontend image from Docker Hub
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - appify_network
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000

  backend:
    image: clintbeastwood/appify-backend:latest # Pull the backend image from Docker Hub
    ports:
      - "5000:5000"
    networks:
      - appify_network
    environment:
      - MONGO_URI=mongodb://mongo:27017/appify
      - JWT_SECRET=bradpittis100%HUNK
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest # Use the official MongoDB image from Docker Hub
    ports:
      - "27017:27017"
    networks:
      - appify_network
    volumes:
      - mongo-data:/data/db

  db-init:
    image: clintbeastwood/appify-db-init:latest # Pull the db-init image from Docker Hub
    depends_on:
      - mongo
    networks:
      - appify_network
    environment:
      - MONGO_URI=mongodb://mongo:27017/appify

networks:
  appify_network:
    driver: bridge

volumes:
  mongo-data: