# Use Node.js image as base
FROM node:16

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY backend/package*.json ./

# Install the backend dependencies
RUN npm install

# Copy the rest of the backend files
COPY ./backend .

# Expose the backend port (e.g., 5000)
EXPOSE 5000

# Command to run your app
CMD ["npm", "start"]
